#!/bin/bash

color=$1

start_with_hash() {
  [[ $1 =~ ^# ]];
}

arg_is_hex_color() {
  [[ $1 =~ ^\#[[:xdigit:]]{6}$ ]];
}

if start_with_hash "$color";
then
  hex_color=$color
else
  hex_color=\#$color
fi

if  arg_is_hex_color "$hex_color";
then
  notify-send -h string:bgcolor:"$hex_color" -h string:fgcolor:"$hex_color" "$RANDOM"
fi
